# .travis.yml
language: node_js
addons:
  apt:
    packages:
      - xvfb
node_js:
  - '5.4'
  - '4.4'
notifications:
  email: false
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install -g vigour-test
